engines:
  reek:
    enabled: true
  flog:
    enabled: true
  rubymotion:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/DefWithParentheses:
        enabled: false
      Rubocop/Style/AsciiComments:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
      Rubocop/Layout/ExtraSpacing:
        enabled: false
      Rubocop/Layout/SpaceAroundOperators:
        enabled: false
      Rubocop/Style/RedundantReturn:
        enabled: false
      Rubocop/Layout/EmptyLinesAroundClassBody:
        enabled: false
      Rubocop/Naming/FileName:
        enabled: false
      Rubocop/Layout/IndentationWidth:
        enabled: false
      Rubocop/Layout/Tab:
        enabled: false
      Rubocop/Naming/VariableName:
        enabled: false
      Rubocop/Style/AndOr:
        enabled: false
      Rubocop/Style/HashSyntax:
        enabled: false
      Rubocop/Style/MethodCallWithoutArgsParentheses:
        enabled: false
      UncommunicativeVariableName:
        enabled: false
      Rubocop/Style/RedundantSelf:
        enabled: false
      Rubocop/Layout/SpaceAfterComma:
        enabled: false
      Rubocop/Layout/EmptyLinesAroundMethodBody:
        enabled: false
