engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AsciiComments:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
      Rubocop/Layout/ExtraSpacing:
         enabled: false
      Rubocop/Layout/SpaceAroundOperators:
         enabled: false
